// Platform world file as a TypeScript string constant.
// Compiled at cold start via parseWorldMarkdown() → emitWorldDefinition().
// This IS the governance. Not a summary. Not a mock. The actual world file.

// In production, this file is generated by: neuroverse bootstrap --input world.nv-world.md
// For now, we inline it so edge functions can import it directly.

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load the ACTUAL world file from disk
// Path: apps/bevia/world.nv-world.md (platform governance)
export let PLATFORM_WORLD_MD: string;

try {
  PLATFORM_WORLD_MD = readFileSync(
    resolve(__dirname, '../../../world.nv-world.md'),
    'utf-8',
  );
} catch {
  // Fallback for Supabase Edge Functions (no filesystem)
  // In this case, the world file should be inlined at build time
  PLATFORM_WORLD_MD = `---
world_id: bevia-platform
name: Bevia Platform Governance
version: 1.0.0
runtime_mode: COMPLIANCE
default_profile: standard
---

# Invariants

- credits_before_action (structural, immutable)
- refund_on_failure (structural, immutable)
- user_data_isolated (structural, immutable)
- governance_on_everything (structural, immutable)
- audit_everything (structural, immutable)
- awareness_not_optimization (structural, immutable)
- show_not_script (structural, immutable)
- never_exploit_emotional_patterns (structural, immutable)
- prediction_is_pattern (structural, immutable)
- user_chooses (structural, immutable)
- no_manipulation_framing (structural, immutable)
- contact_profiles_are_behavioral (structural, immutable)
- simulation_honesty (structural, immutable)
- ai_grounded_in_data (structural, immutable)
- hybrid_rule (structural, immutable)
- user_can_delete_everything (structural, immutable)
- no_cross_tool_data_leak (structural, immutable)
`;
}
